# Generated by Django 5.1.6 on 2025-02-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moduleinstance',
            unique_together={('module', 'year', 'semester')},
        ),
        migrations.AddField(
            model_name='moduleinstance',
            name='professors',
            field=models.ManyToManyField(to='ratings.professor'),
        ),
        migrations.RemoveField(
            model_name='moduleinstance',
            name='professor',
        ),
    ]
