# Generated by Django 5.1.6 on 2025-02-28 17:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_alter_moduleinstance_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('module_instance', 'professor', 'user')},
        ),
    ]
