# Generated by Django 5.1.6 on 2025-03-09 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_professor_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='moduleinstance',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
